name: playwright-bun
on: push
jobs:
  playwright-bun:
    runs-on: [ubuntu-latest,windows-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bunx playwright install
      - run: bun run test
     
